// tag-gapi-builder-start: This file is generated by gapi-builder, DO NOT EDIT.
package city

import (
	__common "github.com/ootiny/gapi/server/gapi/common"
)

type City struct {
	Name string`json:"name" required:"true"`
	Location GeoLocation`json:"location" required:"true"`
	Description string`json:"description"`
}

type GeoLocation = __common.Geo

type FuncGetCity = func(id string) (City, error)
type HookGetCity = func(fn FuncGetCity) error

//tag-gapi-builder-end