// tag-gapi-builder-start: This file is generated by gapi-builder, DO NOT EDIT.
package common

import (
	__system "github.com/ootiny/gapi/server/gapi/__gapi_system__"
)

type Geo struct {
	Latitude float64`json:"latitude" required:"true"`
	Longitude float64`json:"longitude" required:"true"`
}


func init() {
	__system.RegisterHandler("/", func(w __system.IResponse, r __system.IRequest) {

	})
}
//tag-gapi-builder-end