// tag-gapi-builder-start: This file is generated by gapi-builder, DO NOT EDIT.
package common


type Geo struct {
	Latitude float64`json:"latitude" required:"true"`
	Longitude float64`json:"longitude" required:"true"`
}


//tag-gapi-builder-end